batch_size: 2
checkpoint_dir: ./checkpoints/fineweb_edu10-long-small
dataset: fineweb-edu
eval_steps: 10
grad_accum_steps: 4
gradient_checkpointing: false
log_dir: ./logs/fineweb_edu10-long-small
lr: 0.0007
max_steps: 40000
model_size: small
model_type: long
num_workers: 2
output_dir: ./output/fineweb_edu10-long-small
resume_from_checkpoint: null
save_steps: 5000
seq_len: 2048
val_dataset: fineweb-edu
warmup_steps: 700
