batch_size: 64
dataset: slimpajama_6b
eval_steps: 5000
grad_accum_steps: 4
gradient_checkpointing: true
log_dir: ./holo_small_344M
lr: 0.0003
max_steps: 11444
model_size: small
output_dir: ./holo_checkpoints
resume_from_checkpoint: null
save_steps: 5000
seq_len: 2048
val_dataset: slimpajama_6b
warmup_steps: 2000
