batch_size: 2
dataset: slimpajama_6b
eval_steps: 200
grad_accum_steps: 2
log_dir: ./holo_logs
lr: 0.0003
max_steps: 1000
model_size: small
output_dir: ./holo_checkpoints
resume_from_checkpoint: null
save_steps: 200
seq_len: 2048
val_dataset: slimpajama_6b
warmup_steps: 100
