batch_size: 4
checkpoint_dir: ./checkpoints/pg19-long-small
dataset: pg19
eval_steps: 50
grad_accum_steps: 8
gradient_checkpointing: false
log_dir: ./logs/pg19
lr: 0.0007
max_steps: 10000
model_size: small
model_type: long
output_dir: ./output/pg19-long-small
resume_from_checkpoint: null
save_steps: 1000
seq_len: 4096
val_dataset: pg19
warmup_steps: 2000
