batch_size: 16
dataset: slimpajama_6b
eval_steps: 1000
grad_accum_steps: 4
gradient_checkpointing: false
log_dir: ./holo_small_187M_onwards
lr: 0.0003
max_steps: 23000
model_size: small
output_dir: ./holo_checkpoints
resume_from_checkpoint: ./holo_checkpoints/step_12500
save_steps: 2500
seq_len: 2048
val_dataset: slimpajama_6b
warmup_steps: 2000
